<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<main>
<Section>
   
    <h1 style="text-align: center;">Wassap Cuh</h1>
    <h2 style="text-align: center;">Jototot Survey</h2>
    <p style="text-align: center;">Isa kang jototot?</p>  

</Section>
<section>

 <Fieldset>
    <legend style="text-align: center; color: firebrick; font-size: x-large;">Paalala!!</legend>
     <p style="text-align: center;">1.Mag pakatotoo sa sarile</p>   
     <p style="text-align: center;">2.Okay lang maging jototot</p> 
     <p style="text-align: center;">3.Mahal padin kita:)<33333</p> 
</Fieldset>

</section>
<section>
    <form target="_blank" action="https://th.bing.com/th/id/OIP.BcP-Kv5Z-X3vsOZ1lrB1-gHaEU?rs=1&pid=ImgDetMain">
 
        <fieldset>
             <legend>Nakakaramdam ka ba ng pag ka turn on kapag kasama mo ang iyong homies?</legend>
            <label>
                <input name="jototot" checked value="oo" type="radio" id="oo"> Oo
                <input name="jototot" value="Hindi ah" type="radio" id="hindi ah"> Hindi ah
                <input name="jototot" value="Konti lang" type="radio" id="konti lang"> Konti lang
             </label>
        </fieldset>
        
        <fieldset>
            <legend>Pinag jaja-</legend>
           <label>
               <input name="Noway" checked value="oo" type="radio" id="oo"> Oo
               <input name="Noway" value="Hindi ah" type="radio" id="hindi ah"> Hindi ah
               <input name="Noway" value="1 round" type="radio" id="1 round"> 1 round
               <input name="Noway" value="Nakatatlo na" type="radio" id="Nakatatlo na"> Nakatatlo na
           </label>
        </fieldset>
        
        <fieldset>
            <legend>Sinusuportahan moba ang LGBTQ community?</legend>
           <label>
               <input name="yessir" checked value="Syempre" type="radio" id="Syempre"> Syempre
            </label>
        </fieldset>
        
        <fieldset>
            <legend>Mahal mo ba ako?</legend>
           <label>
               <input name="Pinag" checked value="oo" type="radio" id="oo"> Oo
               <input name="Pinag" value="ulol" type="radio" id="Ulol"> Ulol
               <input name="pinag" value="Neutral" type="radio" id="Neutral"> Neutral
               <input name="pinag" value="Pakakasalan na kita" type="radio" id="Pakakasalan na kita"> Pakakasalan na kita
           </label>
        </fieldset>
        <button type="submit">(submit) Pag di mo pinindot ikaw ay jototot</button>
        </form>

        <h1> Advertisement:</h1>
 <img src="https://4.bp.blogspot.com/-s0P17a4qPRc/Vufpy6VlfhI/AAAAAAAACNg/WcU0KB-jIFUI64ASN8OxVLTUSgPh1c12Q/s1600/blowing-a-kiss-emoticon.png" alt="Kissing Emoji" class="my-element">
 <img src="https://i.pinimg.com/originals/5e/9f/12/5e9f12a47ea398fceec9d213ce3c7d62.jpg" alt="Slayy Emoji" class="center">
 <Legend class="text-align">You won iPhone 15 Pro Max!!!</Legend>
 <p>(click the pictue)</p>
 <a target="_blank" href="https://shopee.ph/Apple-iPhone-15-Pro-Max-i.350609763.18799003723?sp_atk=fe1ac7f3-93d1-43b0-ae34-c131e1a83e54&xptdk=fe1ac7f3-93d1-43b0-ae34-c131e1a83e54"><img src="https://itechstore.co.in/uploads/products/15-hero.jpg" alt="iphone 15" class="area"></a>
 <img src="https://pngimg.com/uploads/red_arrow/red_arrow_PNG1.png" alt="arrow" class="arrow">
 <img src="https://i.pinimg.com/originals/31/28/11/312811e13eadf465b62f7ea358eed8a6.png" alt="Wow emoji" class="wow">
<style>
       
 .my-element {
    position: relative;
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 1in;
    top: -4.5in;
    left: 1.9in;
}
 .center {
    position: relative;
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 1.42in;
    top: -5.5in;
    left: -1.9in;
}
   
 .area {
    position: relative;
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 3in;
    top: -1in;
    left: 0in;
}
.arrow {
    position: relative;
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 2in;
    top: -2.5in;
    left: -2.65in;
}
.wow {
    position: relative;
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 2in;
    top: -4in;
    left: 4in;
}
img {
    display: block;
}
  



   </style>




<h4>Maraming salamat sa pag sagot ng aking mga katanungan maaari kanang umalis;)</h4>


</section>





    
  



</main>
</body>
</html>
